# Generated by Django 3.1 on 2021-02-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookchapter',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Номер главы'),
        ),
        migrations.AlterField(
            model_name='bookchapter',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=10),
        ),
    ]
